/**
 * Custom logging level mappings for Pino.
 * Higher priority logs use lower numbers.
 */
export const LEVELS = {
	trace: 10,
	debug: 20,
	info: 30,
	warn: 40,
	error: 50,
	fatal: 60,
} as const;

export const EVENT_NAMES = {
	LIVEZ: "LIVEZ",
	READYZ: "READYZ",
	SIGN_UP: "SIGN_UP",
	SIGN_IN: "SIGN_IN",
	SIGN_OUT: "SIGN_OUT",
	SESSION: "SESSION",

	// No PATIENT_DELETE/REFERRAL_DELETE — hard delete is dropped for both,
	// any role, ever (see `docs/roles-permissions.md`).
	PATIENT_CREATE: "PATIENT_CREATE",
	PATIENT_LIST: "PATIENT_LIST",
	PATIENT_GET: "PATIENT_GET",
	PATIENT_UPDATE: "PATIENT_UPDATE",
	PATIENT_FLAG: "PATIENT_FLAG",
	PATIENT_UNFLAG: "PATIENT_UNFLAG",
	PATIENT_TRANSFER_REQUEST: "PATIENT_TRANSFER_REQUEST",

	REFERRAL_CREATE: "REFERRAL_CREATE",
	REFERRAL_LIST: "REFERRAL_LIST",
	REFERRAL_GET: "REFERRAL_GET",
	REFERRAL_UPDATE: "REFERRAL_UPDATE",
	REFERRAL_STATUS_UPDATE: "REFERRAL_STATUS_UPDATE",
	REFERRAL_HISTORY: "REFERRAL_HISTORY",
	REFERRAL_ASSIGN: "REFERRAL_ASSIGN",
	REFERRAL_REDIRECT: "REFERRAL_REDIRECT",
	REFERRAL_SPECIALTY_LIST: "REFERRAL_SPECIALTY_LIST",
	REFERRAL_SPECIALTY_ASSIGN: "REFERRAL_SPECIALTY_ASSIGN",
	REFERRAL_SPECIALTY_UNASSIGN: "REFERRAL_SPECIALTY_UNASSIGN",

	// No FACILITY_CREATE — `POST /facilities` is removed (see
	// `modules/facilities/route.ts`): the creation-time invariant means a
	// facility only ever comes into being via a Manager's registration
	// (`SIGN_UP`), never a direct create call by anyone, Administrator
	// included.
	SPECIALTY_LIST: "SPECIALTY_LIST",
	SPECIALTY_GET: "SPECIALTY_GET",
	SPECIALTY_CREATE: "SPECIALTY_CREATE",
	SPECIALTY_UPDATE: "SPECIALTY_UPDATE",

	FACILITY_LIST: "FACILITY_LIST",
	FACILITY_GET: "FACILITY_GET",
	FACILITY_UPDATE: "FACILITY_UPDATE",
	FACILITY_HISTORY: "FACILITY_HISTORY",
	FACILITY_SPECIALTY_LIST: "FACILITY_SPECIALTY_LIST",
	FACILITY_SPECIALTY_ASSIGN: "FACILITY_SPECIALTY_ASSIGN",
	FACILITY_SPECIALTY_UNASSIGN: "FACILITY_SPECIALTY_UNASSIGN",

	AUDIT_LOGINS: "AUDIT_LOGINS",

	// No USER_DISABLE — `PATCH /users/:id/disable` is removed, superseded
	// by the role-first moderation endpoints below (which always record a
	// reason; the old endpoint didn't).
	USER_LIST: "USER_LIST",
	USER_GET: "USER_GET",
	USER_HISTORY: "USER_HISTORY",
	USER_SPECIALTY_LIST: "USER_SPECIALTY_LIST",
	USER_SPECIALTY_ASSIGN: "USER_SPECIALTY_ASSIGN",
	USER_SPECIALTY_UNASSIGN: "USER_SPECIALTY_UNASSIGN",

	DASHBOARD_NURSE_SUMMARY: "DASHBOARD_NURSE_SUMMARY",
	DASHBOARD_DOCTOR_SUMMARY: "DASHBOARD_DOCTOR_SUMMARY",
	DASHBOARD_ADMIN_SUMMARY: "DASHBOARD_ADMIN_SUMMARY",
	DASHBOARD_MANAGER_SUMMARY: "DASHBOARD_MANAGER_SUMMARY",

	REPORTS_REFERRALS: "REPORTS_REFERRALS",

	// Self-service — `modules/account`.
	ACCOUNT_STATUS: "ACCOUNT_STATUS",
	ACCOUNT_APPEAL: "ACCOUNT_APPEAL",
	ACCOUNT_CHANGE_PASSWORD: "ACCOUNT_CHANGE_PASSWORD",

	// Administrator-only — `modules/administrator`.
	ADMINISTRATOR_MANAGER_APPROVE: "ADMINISTRATOR_MANAGER_APPROVE",
	ADMINISTRATOR_MANAGER_REJECT: "ADMINISTRATOR_MANAGER_REJECT",
	ADMINISTRATOR_MANAGER_DISABLE: "ADMINISTRATOR_MANAGER_DISABLE",
	ADMINISTRATOR_MANAGER_FLAG: "ADMINISTRATOR_MANAGER_FLAG",
	ADMINISTRATOR_STAFF_APPROVE: "ADMINISTRATOR_STAFF_APPROVE",
	ADMINISTRATOR_STAFF_REJECT: "ADMINISTRATOR_STAFF_REJECT",
	ADMINISTRATOR_STAFF_FLAG: "ADMINISTRATOR_STAFF_FLAG",
	ADMINISTRATOR_STAFF_DISABLE: "ADMINISTRATOR_STAFF_DISABLE",
	ADMINISTRATOR_FACILITY_APPROVE: "ADMINISTRATOR_FACILITY_APPROVE",
	ADMINISTRATOR_FACILITY_REJECT: "ADMINISTRATOR_FACILITY_REJECT",
	ADMINISTRATOR_FACILITY_FLAG: "ADMINISTRATOR_FACILITY_FLAG",
	ADMINISTRATOR_FACILITY_SUSPEND: "ADMINISTRATOR_FACILITY_SUSPEND",
	ADMINISTRATOR_USER_CREATE: "ADMINISTRATOR_USER_CREATE",
	ADMINISTRATOR_USER_RESET_PASSWORD: "ADMINISTRATOR_USER_RESET_PASSWORD",
	ADMINISTRATOR_APPEAL_APPROVE: "ADMINISTRATOR_APPEAL_APPROVE",
	ADMINISTRATOR_APPEAL_DENY: "ADMINISTRATOR_APPEAL_DENY",
	ADMINISTRATOR_APPEAL_LIST: "ADMINISTRATOR_APPEAL_LIST",
	ADMINISTRATOR_TRANSFER_ORIGIN_APPROVE:
		"ADMINISTRATOR_TRANSFER_ORIGIN_APPROVE",
	ADMINISTRATOR_TRANSFER_ORIGIN_REJECT: "ADMINISTRATOR_TRANSFER_ORIGIN_REJECT",
	ADMINISTRATOR_TRANSFER_DESTINATION_APPROVE:
		"ADMINISTRATOR_TRANSFER_DESTINATION_APPROVE",
	ADMINISTRATOR_TRANSFER_DESTINATION_REJECT:
		"ADMINISTRATOR_TRANSFER_DESTINATION_REJECT",
	ADMINISTRATOR_TRANSFER_LIST: "ADMINISTRATOR_TRANSFER_LIST",

	// Manager-only — `modules/manager`.
	MANAGER_STAFF_APPROVE: "MANAGER_STAFF_APPROVE",
	MANAGER_STAFF_REJECT: "MANAGER_STAFF_REJECT",
	MANAGER_STAFF_DISABLE: "MANAGER_STAFF_DISABLE",
	MANAGER_STAFF_FLAG: "MANAGER_STAFF_FLAG",
	MANAGER_FACILITY_APPEAL: "MANAGER_FACILITY_APPEAL",
	MANAGER_APPEAL_APPROVE: "MANAGER_APPEAL_APPROVE",
	MANAGER_APPEAL_DENY: "MANAGER_APPEAL_DENY",
	MANAGER_APPEAL_LIST: "MANAGER_APPEAL_LIST",
	MANAGER_TRANSFER_ORIGIN_APPROVE: "MANAGER_TRANSFER_ORIGIN_APPROVE",
	MANAGER_TRANSFER_ORIGIN_REJECT: "MANAGER_TRANSFER_ORIGIN_REJECT",
	MANAGER_TRANSFER_DESTINATION_APPROVE: "MANAGER_TRANSFER_DESTINATION_APPROVE",
	MANAGER_TRANSFER_DESTINATION_REJECT: "MANAGER_TRANSFER_DESTINATION_REJECT",
	MANAGER_TRANSFER_LIST: "MANAGER_TRANSFER_LIST",
	MANAGER_AUDIT_LIST: "MANAGER_AUDIT_LIST",
} as const;
